Encuestas/urls.py
from django.urls import path

from . import views

app_name = 'Encuestas'
urlpatterns = [
    path('', views.VistaDeIndex.as_view(), name='index'),
    path('<int:pk>/', views.VistaDeDetalles.as_view(), name='detalles'),
    path('<int:pk>/resultados/', views.VistaDeResultados.as_view(), name='resultados'),
    path('<int:IdDePregunta>/Voto/', views.Voto, name='Voto'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('Encuestas/', include('Encuestas.urls')),
    path('admin/', admin.site.urls),
]

Encuestas/models.py
from django.db import models


class Pregunta(models.Model):
    TextoDePregunta = models.CharField(max_length=200)
    FechaDePublicacion = models.DateTimeField('date published')

    def __str__(self):
        return self.TextoDePregunta


class Eleccion(models.Model):
    Pregunta = models.ForeignKey(Pregunta, on_delete=models.CASCADE)
    TextoDeEleccion = models.CharField(max_length=200)
    Votos = models.IntegerField(default=0)

    def __str__(self):
        return self.TextoDeEleccion

Encuestas/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Eleccion, Pregunta


class VistaDeIndex(generic.ListView):
    NombreTemplate = 'Encuestas/index.html'
    NombreContexto = 'UltimaListaDePreguntas'

    def get_queryset(self):
        return Pregunta.objects.order_by('-FechaDePublicacion')[:5]


class VistaDeDetalles(generic.DetailView):
    Modelo = Pregunta
    NombreTemplate = 'Encuestas/detalle.html'


class VistaDeResultados(generic.DetailView):
    model = Pregunta
    NombreTemplate = 'Encuestas/resultados.html'

def Voto(Solicitud, IdPregunta):
    pregunta = get_object_or_404(Pregunta, pk=IdPregunta)
    try:
        EleccionSeleccionada = pregunta.eleccion_set.get(pk=Solicitud.POST['eleccion'])
    except (KeyError, Eleccion.DoesNotExist):
        return render(Solicitud, 'Encuestas/detalle.html', {
            'Pregunta': pregunta,
            'MensajeDeError': "No seleccionaste una elección.",
        })
    else:
        EleccionSeleccionada.votos += 1
        EleccionSeleccionada.save()
        return HttpResponseRedirect(reverse('Encuestas:resultados', args=(pregunta.id,)))

Encuestas/templates/Encuestas/detalle.html
<h1>{{ pregunta.TextoDePregunta }}</h1>

{% if MensajeDeError %}<p><strong>{{ MensajeDeError }}</strong></p>{% endif %}

<form action="{% url 'Encuestas:Voto' preguntas.id %}" method="post">
{% csrf_token %}
{% for eleccion in pregunta.eleccion_set.all %}
    <input type="radio" name="eleccion" id="eleccion{{ forloop.counter }}" value="{{ eleccion.id }}">
    <label for="eleccion{{ forloop.counter }}">{{ eleccion.TextoDeEleccion }}</label><br>
{% endfor %}
<input type="submit" value="Voto">
</form>

Encuestas/templates/Encuestas/index.html
{% if UltimaListaDePreguntas %}
    <ul>
    {% for pregunta in UltimaListaDePreguntas %}
        <li><a href="{% url 'Encuestas:detalles' pregunta.id %}">{{ pregunta.TextoDePregunta }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No hay Encuestas.</p>
{% endif %}

Encuestas/templates/Encuestas/resultados.html
<h1>{{ pregunta.TextoDePregunta }}</h1>

<ul>
{% for eleccion in pregunta.eleccion_set.all %}
    <li>{{ eleccion.TextoDeEleccion }} -- {{ eleccion.votos }} Voto{{ eleccion.votos|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'encuestas:detalles' pregunta.id %}">¿Desea Votar de Nuevo?</a>